version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1 
          MONGO_URI: mongodb://localhost:27017/loftly-core-testing-db
          SECRET: loftlycoretestingsecret
      - image: mongo:4.2.0 
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install 

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test