version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/loftly-core # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:12.13.1 # ...with this image as the primary container; this is where all `steps` will run
        environment:
          MONGO_URI: mongodb://localhost:27017/loftly-core-testing-db
          SECRET: loftlycoretestingsecret
      - image: mongo:4.2.0 # and this image as the secondary service container
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test